apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sprint-apps-helm-secret
  namespace: argocd
spec:
  project: spring-apps
  source:
    repoURL: https://github.com/xczdev/formation-argocd-repo-secret.git
    targetRevision: HEAD
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: spring-apps-dev